version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: db_owner
      POSTGRES_PASSWORD: 5555
      POSTGRES_DB: softcart
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/schema
      - ./data:/data
      - pgdata:/var/lib/postgresql/data

# to create ERD diagram
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: db_owner@example.com
      PGADMIN_DEFAULT_PASSWORD: 5555
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
