version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data:/data/import
      - ./exports:/data/export

volumes:
  mongodb_data:
